name: 'get-custom'
on:
  push


jobs:
  capture-pr-number:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Ensure jq is installed
      - name: Install jq
        run: sudo apt-get install jq

      - name: Get Template Origin
        id: get-pr-number
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          saida=$(curl --request GET \
          --url "https://api.github.com/repos/NunesHome/repo_wfls_actions_learn/properties/values" \
          -H "Content-Type: application/json" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $GITHUB_TOKEN")

          ##template_origem=$( echo "$saida" | jq '.["template_repository"]["name"]' )

          custom_value=$( echo "$saida" | jq -r '.[] | select(.property_name == "custom_property1_name") | .value')

          echo $custom_value
          
          echo $template_origem
          echo $saida
          echo "template_origem=$template_origem" >> $GITHUB_OUTPUT
      
      - name: Generate Error Annotations
        run: |
          echo "::notice::Este repositorio esta com este TEMPLATE EM SUA ORIGEM: ${{steps.get-pr-number.outputs.template_origem}}"

      - name: Echo github obj
        run: | 
          ruleset=$(echo '${{ toJson(github) }}' | jq '.. | .custom_properties? // empty | .custom_property1_name? // empty')
          echo $ruleset